//Auth Actions
export const AUTH_START = 'AUTH_START';
export const AUTH_SUCCESS = 'AUTH_SUCCESS';
export const AUTH_FAIL = 'AUTH_FAIL';
export const AUTH_LOGOUT = 'AUTH_LOGOUT';

//Start Setting Actions
export const FETCH_SAVED_START_SETTINGS_START = 'FETCH_SAVED_START_SETTINGS_START';
export const FETCH_SAVED_START_SETTINGS_SUCCESS = 'FETCH_SAVED_START_SETTINGS_SUCCESS';
export const FETCH_SAVED_START_SETTINGS_FAIL = 'FETCH_SAVED_START_SETTINGS_FAIL';

export const APPLY_SELECTED_START_SETTINGS_OPTION = 'APPLY_SELECTED_START_SETTINGS_OPTION';

export const ADD_NEW_TIME_SLOT = 'ADD_NEW_TIME_SLOT';
export const DELETE_TIME_SLOT = 'DELETE_TIME_SLOT';
export const UPDATE_TIME_SLOT_DATA = 'UPDATE_TIME_SLOT_DATA';

export const EDIT_STUDENT_CHOICES = 'EDIT_STUDENT_CHOICES';
export const SET_CHOICE_DUPLICATES = 'SET_CHOICE_DUPLICATES';

export const EDIT_START_SETTINGS_TITLE = 'EDIT_START_SETTINGS_TITLE';
export const TOGGLE_START_SETTINGS_CONTINUE = 'TOGGLE_START_SETTINGS_CONTINUE';

export const SAVE_START_SETTINGS_START = 'SAVE_START_SETTINGS_START';
export const SAVE_START_SETTINGS_SUCCESS = 'SAVE_START_SETTINGS_SUCCESS';
export const SAVE_START_SETTINGS_FAIL = 'SAVE_START_SETTINGS_FAIL';

export const RESET_START_DATA = 'RESET_START_DATA';

//Schedule Actions
export const FETCH_SAVED_SCHEDULES_START = 'FETCH_SAVED_SCHEDULES_START';
export const FETCH_SAVED_SCHEDULES_SUCCESS = 'FETCH_SAVED_SCHEDULES_SUCCESS';
export const FETCH_SAVED_SCHEDULES_FAIL = 'FETCH_SAVED_SCHEDULES_FAIL';

export const APPLY_SELECTED_SCHEDULE_OPTION = 'APPLY_SELECTED_SCHEDULE_OPTION';
export const INTEGRATE_SCHEDULE_OPTION = 'INTEGRATE_SCHEDULE_OPTION';

export const ADD_NEW_ROW = 'ADD_NEW_ROW';
export const DELETE_ROW = 'DELETE_ROW';
export const UPDATE_SCHEDULE_DATA = 'UPDATE_SCHEDULE_DATA';

export const EDIT_SCHEDULE_TITLE = 'EDIT_SCHEDULE_TITLE';
export const TOGGLE_SCHEDULE_CONTINUE = 'TOGGLE_SCHEDULE_CONTINUE';

export const SAVE_SCHEDULE_START = 'SAVE_SCHEDULE_START';
export const SAVE_SCHEDULE_SUCCESS = 'SAVE_SCHEDULE_SUCCESS';
export const SAVE_SCHEDULE_FAIL = 'SAVE_SCHEDULE_FAIL';

export const RESET_SCHEDULE_DATA = 'RESET_SCHEDULE_DATA';

//Student Actions
export const FETCH_SAVED_STUDENT_LISTS_START = 'FETCH_SAVED_STUDENT_LISTS_START';
export const FETCH_SAVED_STUDENT_LISTS_SUCCESS = 'FETCH_SAVED_STUDENT_LISTS_SUCCESS';
export const FETCH_SAVED_STUDENT_LISTS_FAIL = 'FETCH_SAVED_STUDENT_LISTS_FAIL';

export const APPLY_SELECTED_STUDENT_LIST_OPTION = 'APPLY_SELECTED_STUDENT_LIST_OPTION';
export const INTEGRATE_STUDENT_LIST_OPTION = 'INTEGRATE_STUDENT_LIST_OPTION';

export const ADD_NEW_STUDENT = 'ADD_NEW_STUDENT';
export const DELETE_STUDENT = 'DELETE_STUDENT';
export const UPDATE_STUDENT_DATA = 'UPDATE_STUDENT_DATA';

export const EDIT_STUDENT_LIST_TITLE = 'EDIT_STUDENT_LIST_TITLE';
export const TOGGLE_STUDENT_LIST_CONTINUE = 'TOGGLE_STUDENT_LIST_CONTINUE';

export const SAVE_STUDENTS_SUCCESS = 'SAVE_STUDENTS_SUCCESS';
export const SAVE_STUDENTS_FAIL = 'SAVE_STUDENTS_FAIL';
export const SAVE_STUDENTS_START = 'SAVE_STUDENTS_START';

export const RESET_STUDENT_DATA = 'RESET_STUDENT_DATA';
