//Auth Actions
export const AUTH_START = 'AUTH_START';
export const AUTH_SUCCESS = 'AUTH_SUCCESS';
export const AUTH_FAIL = 'AUTH_FAIL';
export const AUTH_LOGOUT = 'AUTH_LOGOUT';

//Start Actions
export const FETCH_SAVED_SCHEDULES_START = 'FETCH_SAVED_SCHEDULES_START';
export const FETCH_SAVED_SCHEDULES_SUCCESS = 'FETCH_SAVED_SCHEDULES_SUCCESS';
export const FETCH_SAVED_SCHEDULES_FAIL = 'FETCH_SAVED_SCHEDULES_FAIL';

export const FETCH_SAVED_STUDENT_LISTS_START = 'FETCH_SAVED_STUDENT_LISTS_START';
export const FETCH_SAVED_STUDENT_LISTS_SUCCESS = 'FETCH_SAVED_STUDENT_LISTS_SUCCESS';
export const FETCH_SAVED_STUDENT_LISTS_FAIL = 'FETCH_SAVED_STUDENT_LISTS_FAIL';

export const SET_SCHEDULE_OPTION = 'SET_SCHEDULE_OPTION'
export const SELECT_SCHEDULE = 'SELECT_SCHEDULE';

export const SET_STUDENT_OPTION = 'SET_STUDENT_OPTION';
export const SELECT_STUDENT_LIST = 'SELECT_STUDENT_LIST';

export const SET_CHOICE_OPTION = 'SET_CHOICE_OPTION';
export const SET_CHOICE_DUPLICATES = 'SET_CHOICE_DUPLICATES';

export const SET_SORT_OPTION = 'SET_SORT_OPTION';

//Schedule Actions
export const ADD_NEW_ROW = 'ADD_NEW_ROW';
export const DELETE_ROW = 'DELETE_ROW';
export const UPDATE_SCHEDULE_DATA = 'UPDATE_SCHEDULE_DATA';
export const EDIT_SCHEDULE_TITLE = 'EDIT_SCHEDULE_TITLE';

export const APPLY_SELECTED_LOAD_OPTION = 'APPLY_SELECTED_LOAD_OPTION';

export const SAVE_SCHEDULE_START = 'SAVE_SCHEDULE_START';
export const SAVE_SCHEDULE_SUCCESS = 'SAVE_SCHEDULE_SUCCESS';
export const SAVE_SCHEDULE_FAIL = 'SAVE_SCHEDULE_FAIL';

export const SET_SCHEDULE_DATA = 'SET_SCHEDULE_DATA';
export const RESET_SCHEDULE_DATA = 'RESET_SCHEDULE_DATA';

//Student Actions
export const ADD_NEW_STUDENT = 'ADD_NEW_STUDENT';
export const DELETE_STUDENT = 'DELETE_STUDENT';

export const UPDATE_STUDENT_DATA = 'UPDATE_STUDENT_DATA';
export const EDIT_STUDENT_LIST_TITLE = 'EDIT_STUDENT_LIST_TITLE';

export const SAVE_STUDENTS_SUCCESS = 'SAVE_STUDENTS_SUCCESS';
export const SAVE_STUDENTS_FAIL = 'SAVE_STUDENTS_FAIL';
export const SAVE_STUDENTS_START = 'SAVE_STUDENTS_START';

export const SET_STUDENT_DATA = 'SET_STUDENT_DATA';
export const RESET_STUDENT_DATA = 'RESET_STUDENT_DATA';
